export interface ToolMeta {
  slug: string;
  icon: string; // nom d'icône lucide
  titleFr: string; titleEn: string;
  descFr: string; descEn: string;
  keywords: string[];
  premium?: boolean;
}

export const tools: ToolMeta[] = [
  { slug: 'currency-converter', icon: 'Coins',
    titleFr: 'Convertisseur de devises', titleEn: 'Currency Converter',
    descFr: 'Convertissez toutes les devises mondiales en temps réel avec historique des taux.',
    descEn: 'Convert all world currencies in real time with rate history.',
    keywords: ['convertisseur devises','taux de change','currency converter','exchange rate'] },
  { slug: 'document-generator', icon: 'FileText',
    titleFr: 'Générateur de documents administratifs', titleEn: 'Administrative Document Generator',
    descFr: 'Générez lettres, attestations, factures, devis et contrats puis exportez en PDF.',
    descEn: 'Generate letters, certificates, invoices, quotes and contracts then export to PDF.',
    keywords: ['lettre de motivation','attestation','facture','devis','contrat','modèle document'] },
  { slug: 'text-corrector', icon: 'SpellCheck',
    titleFr: 'Correction & reformulation de texte', titleEn: 'Text Correction & Rewriting',
    descFr: 'Corrigez l\'orthographe, la grammaire et reformulez vos textes (formel, persuasif, simplifié).',
    descEn: 'Fix spelling, grammar and rewrite your text (formal, persuasive, simplified).',
    keywords: ['correction orthographe','grammaire','reformulation','rewriting'] },
  { slug: 'loan-calculator', icon: 'Landmark',
    titleFr: 'Calculateur de prêt', titleEn: 'Loan Calculator',
    descFr: 'Calculez mensualités, intérêts, coût total et tableau d\'amortissement avec graphiques.',
    descEn: 'Compute monthly payments, interest, total cost and amortization schedule with charts.',
    keywords: ['calcul prêt','mensualité','amortissement','simulation crédit','loan calculator'] },
  { slug: 'unit-converter', icon: 'Ruler',
    titleFr: 'Convertisseur universel', titleEn: 'Universal Converter',
    descFr: 'Convertissez distance, poids, température, volume, vitesse, énergie, stockage et plus.',
    descEn: 'Convert distance, weight, temperature, volume, speed, energy, storage and more.',
    keywords: ['convertisseur unités','température','poids','distance','unit converter'] },
  { slug: 'adsense-calculator', icon: 'TrendingUp',
    titleFr: 'Vérificateur de rentabilité AdSense', titleEn: 'AdSense Revenue Estimator',
    descFr: 'Estimez vos revenus AdSense quotidiens, mensuels et annuels selon trafic, CTR et CPC.',
    descEn: 'Estimate daily, monthly and yearly AdSense revenue from traffic, CTR and CPC.',
    keywords: ['adsense','revenus','cpc','ctr','rpm','monetisation'] },
  { slug: 'cv-generator', icon: 'User',
    titleFr: 'Générateur de CV professionnels', titleEn: 'Professional CV Generator',
    descFr: 'Créez un CV moderne et ATS-friendly avec aperçu en temps réel et export PDF.',
    descEn: 'Create a modern, ATS-friendly resume with live preview and PDF export.',
    keywords: ['cv','curriculum vitae','resume','ats','modèle cv'], premium: true },
  { slug: 'banner-generator', icon: 'Image',
    titleFr: 'Générateur de bannières publicitaires', titleEn: 'Ad Banner Generator',
    descFr: 'Créez des bannières Facebook, Instagram, Google Ads, LinkedIn, YouTube (PNG/PDF).',
    descEn: 'Create Facebook, Instagram, Google Ads, LinkedIn, YouTube banners (PNG/PDF).',
    keywords: ['bannière','publicité','ad banner','facebook','instagram','google ads'], premium: true },
  { slug: 'json-formatter', icon: 'Braces',
    titleFr: 'Formateur JSON', titleEn: 'JSON Formatter',
    descFr: 'Formatez, validez et minifiez votre JSON instantanement, avec coloration et detection des erreurs.',
    descEn: 'Format, validate and minify your JSON instantly, with highlighting and error detection.',
    keywords: ["json","formateur json","json formatter","beautify json","minify json"] },
  { slug: 'json-xml', icon: 'FileCode',
    titleFr: 'Convertisseur JSON / XML', titleEn: 'JSON / XML Converter',
    descFr: 'Convertissez vos donnees entre JSON et XML dans les deux sens, en un clic.',
    descEn: 'Convert your data between JSON and XML both ways, in one click.',
    keywords: ["json xml","convertisseur xml","json to xml","xml to json"] },
  { slug: 'base64', icon: 'Binary',
    titleFr: 'Encodeur / Decodeur Base64', titleEn: 'Base64 Encoder / Decoder',
    descFr: 'Encodez et decodez du texte en Base64 instantanement, support UTF-8 complet.',
    descEn: 'Encode and decode text to Base64 instantly, full UTF-8 support.',
    keywords: ["base64","encoder","decoder","encodeur base64","decodeur base64"] },
  { slug: 'uuid-generator', icon: 'Fingerprint',
    titleFr: 'Generateur UUID', titleEn: 'UUID Generator',
    descFr: 'Generez des UUID v4 aleatoires en masse, copiables en un clic.',
    descEn: 'Generate random v4 UUIDs in bulk, copy in one click.',
    keywords: ["uuid","guid","generateur uuid","uuid v4","unique id"] },
  { slug: 'password-generator', icon: 'KeyRound',
    titleFr: 'Generateur de mots de passe', titleEn: 'Password Generator',
    descFr: 'Creez des mots de passe forts et personnalisables avec indicateur de robustesse.',
    descEn: 'Create strong, customizable passwords with a strength meter.',
    keywords: ["mot de passe","password generator","generateur mot de passe","securite"] },
  { slug: 'api-key-generator', icon: 'Key',
    titleFr: 'Generateur de cles API fictives', titleEn: 'Mock API Key Generator',
    descFr: 'Generez des cles API et tokens fictifs pour vos tests (plusieurs formats).',
    descEn: 'Generate fake API keys and tokens for your tests (multiple formats).',
    keywords: ["cle api","api key","token","test","mock api key","generateur cle"] },
  { slug: 'sitemap-generator', icon: 'Map',
    titleFr: 'Generateur de sitemap XML', titleEn: 'XML Sitemap Generator',
    descFr: 'Generez un sitemap.xml valide a partir de vos URLs, pret pour Google Search Console.',
    descEn: 'Generate a valid sitemap.xml from your URLs, ready for Google Search Console.',
    keywords: ["sitemap","sitemap xml","seo","google","generateur sitemap"] },
  { slug: 'robots-generator', icon: 'Bot',
    titleFr: 'Generateur de robots.txt', titleEn: 'robots.txt Generator',
    descFr: 'Creez un fichier robots.txt optimise pour controler l’exploration des moteurs de recherche.',
    descEn: 'Create an optimized robots.txt to control search engine crawling.',
    keywords: ["robots.txt","seo","crawl","googlebot","generateur robots"] },
  { slug: 'schema-generator', icon: 'Code2',
    titleFr: 'Generateur de schemas Schema.org', titleEn: 'Schema.org Generator',
    descFr: 'Generez des donnees structurees JSON-LD (Article, Product, FAQ, LocalBusiness...) pour le SEO.',
    descEn: 'Generate JSON-LD structured data (Article, Product, FAQ, LocalBusiness...) for SEO.',
    keywords: ["schema.org","json-ld","donnees structurees","rich snippets","seo"] },
  { slug: 'qr-code', icon: 'QrCode',
    titleFr: 'Generateur de QR Code', titleEn: 'QR Code Generator',
    descFr: 'Creez des QR codes personnalisables (URL, texte, contact) et telechargez-les en PNG.',
    descEn: 'Create customizable QR codes (URL, text, contact) and download them as PNG.',
    keywords: ["qr code","qrcode","generateur qr","code qr"] },
  { slug: 'color-palette', icon: 'Palette',
    titleFr: 'Generateur de palettes de couleurs', titleEn: 'Color Palette Generator',
    descFr: 'Generez des palettes harmonieuses, copiez les codes HEX et exportez vos couleurs.',
    descEn: 'Generate harmonious palettes, copy HEX codes and export your colors.',
    keywords: ["palette","couleurs","hex","design","generateur palette","color"] },
];

export const getTool = (slug: string) => tools.find(t => t.slug === slug);