export interface ToolMeta {
  slug: string;
  icon: string; // nom d'icône lucide
  titleFr: string; titleEn: string;
  descFr: string; descEn: string;
  keywords: string[];
  premium?: boolean;
}

export const tools: ToolMeta[] = [
  { slug: 'currency-converter', icon: 'Coins',
    titleFr: 'Convertisseur de devises', titleEn: 'Currency Converter',
    descFr: 'Convertissez toutes les devises mondiales en temps réel avec historique des taux.',
    descEn: 'Convert all world currencies in real time with rate history.',
    keywords: ['convertisseur devises','taux de change','currency converter','exchange rate'] },
  { slug: 'document-generator', icon: 'FileText',
    titleFr: 'Générateur de documents administratifs', titleEn: 'Administrative Document Generator',
    descFr: 'Générez lettres, attestations, factures, devis et contrats puis exportez en PDF.',
    descEn: 'Generate letters, certificates, invoices, quotes and contracts then export to PDF.',
    keywords: ['lettre de motivation','attestation','facture','devis','contrat','modèle document'] },
  { slug: 'text-corrector', icon: 'SpellCheck',
    titleFr: 'Correction & reformulation de texte', titleEn: 'Text Correction & Rewriting',
    descFr: 'Corrigez l\'orthographe, la grammaire et reformulez vos textes (formel, persuasif, simplifié).',
    descEn: 'Fix spelling, grammar and rewrite your text (formal, persuasive, simplified).',
    keywords: ['correction orthographe','grammaire','reformulation','rewriting'] },
  { slug: 'loan-calculator', icon: 'Landmark',
    titleFr: 'Calculateur de prêt', titleEn: 'Loan Calculator',
    descFr: 'Calculez mensualités, intérêts, coût total et tableau d\'amortissement avec graphiques.',
    descEn: 'Compute monthly payments, interest, total cost and amortization schedule with charts.',
    keywords: ['calcul prêt','mensualité','amortissement','simulation crédit','loan calculator'] },
  { slug: 'unit-converter', icon: 'Ruler',
    titleFr: 'Convertisseur universel', titleEn: 'Universal Converter',
    descFr: 'Convertissez distance, poids, température, volume, vitesse, énergie, stockage et plus.',
    descEn: 'Convert distance, weight, temperature, volume, speed, energy, storage and more.',
    keywords: ['convertisseur unités','température','poids','distance','unit converter'] },
  { slug: 'adsense-calculator', icon: 'TrendingUp',
    titleFr: 'Vérificateur de rentabilité AdSense', titleEn: 'AdSense Revenue Estimator',
    descFr: 'Estimez vos revenus AdSense quotidiens, mensuels et annuels selon trafic, CTR et CPC.',
    descEn: 'Estimate daily, monthly and yearly AdSense revenue from traffic, CTR and CPC.',
    keywords: ['adsense','revenus','cpc','ctr','rpm','monetisation'] },
  { slug: 'cv-generator', icon: 'User',
    titleFr: 'Générateur de CV professionnels', titleEn: 'Professional CV Generator',
    descFr: 'Créez un CV moderne et ATS-friendly avec aperçu en temps réel et export PDF.',
    descEn: 'Create a modern, ATS-friendly resume with live preview and PDF export.',
    keywords: ['cv','curriculum vitae','resume','ats','modèle cv'], premium: true },
  { slug: 'banner-generator', icon: 'Image',
    titleFr: 'Générateur de bannières publicitaires', titleEn: 'Ad Banner Generator',
    descFr: 'Créez des bannières Facebook, Instagram, Google Ads, LinkedIn, YouTube (PNG/PDF).',
    descEn: 'Create Facebook, Instagram, Google Ads, LinkedIn, YouTube banners (PNG/PDF).',
    keywords: ['bannière','publicité','ad banner','facebook','instagram','google ads'], premium: true },
  { slug: 'json-formatter', icon: 'Braces',
    titleFr: 'Formateur JSON', titleEn: 'JSON Formatter',
    descFr: 'Formatez, validez et minifiez votre JSON instantanement, avec coloration et detection des erreurs.',
    descEn: 'Format, validate and minify your JSON instantly, with highlighting and error detection.',
    keywords: ["json","formateur json","json formatter","beautify json","minify json"] },
  { slug: 'json-xml', icon: 'FileCode',
    titleFr: 'Convertisseur JSON / XML', titleEn: 'JSON / XML Converter',
    descFr: 'Convertissez vos donnees entre JSON et XML dans les deux sens, en un clic.',
    descEn: 'Convert your data between JSON and XML both ways, in one click.',
    keywords: ["json xml","convertisseur xml","json to xml","xml to json"] },
  { slug: 'base64', icon: 'Binary',
    titleFr: 'Encodeur / Decodeur Base64', titleEn: 'Base64 Encoder / Decoder',
    descFr: 'Encodez et decodez du texte en Base64 instantanement, support UTF-8 complet.',
    descEn: 'Encode and decode text to Base64 instantly, full UTF-8 support.',
    keywords: ["base64","encoder","decoder","encodeur base64","decodeur base64"] },
  { slug: 'uuid-generator', icon: 'Fingerprint',
    titleFr: 'Generateur UUID', titleEn: 'UUID Generator',
    descFr: 'Generez des UUID v4 aleatoires en masse, copiables en un clic.',
    descEn: 'Generate random v4 UUIDs in bulk, copy in one click.',
    keywords: ["uuid","guid","generateur uuid","uuid v4","unique id"] },
  { slug: 'password-generator', icon: 'KeyRound',
    titleFr: 'Generateur de mots de passe', titleEn: 'Password Generator',
    descFr: 'Creez des mots de passe forts et personnalisables avec indicateur de robustesse.',
    descEn: 'Create strong, customizable passwords with a strength meter.',
    keywords: ["mot de passe","password generator","generateur mot de passe","securite"] },
  { slug: 'api-key-generator', icon: 'Key',
    titleFr: 'Generateur de cles API fictives', titleEn: 'Mock API Key Generator',
    descFr: 'Generez des cles API et tokens fictifs pour vos tests (plusieurs formats).',
    descEn: 'Generate fake API keys and tokens for your tests (multiple formats).',
    keywords: ["cle api","api key","token","test","mock api key","generateur cle"] },
  { slug: 'sitemap-generator', icon: 'Map',
    titleFr: 'Generateur de sitemap XML', titleEn: 'XML Sitemap Generator',
    descFr: 'Generez un sitemap.xml valide a partir de vos URLs, pret pour Google Search Console.',
    descEn: 'Generate a valid sitemap.xml from your URLs, ready for Google Search Console.',
    keywords: ["sitemap","sitemap xml","seo","google","generateur sitemap"] },
  { slug: 'robots-generator', icon: 'Bot',
    titleFr: 'Generateur de robots.txt', titleEn: 'robots.txt Generator',
    descFr: 'Creez un fichier robots.txt optimise pour controler l’exploration des moteurs de recherche.',
    descEn: 'Create an optimized robots.txt to control search engine crawling.',
    keywords: ["robots.txt","seo","crawl","googlebot","generateur robots"] },
  { slug: 'schema-generator', icon: 'Code2',
    titleFr: 'Generateur de schemas Schema.org', titleEn: 'Schema.org Generator',
    descFr: 'Generez des donnees structurees JSON-LD (Article, Product, FAQ, LocalBusiness...) pour le SEO.',
    descEn: 'Generate JSON-LD structured data (Article, Product, FAQ, LocalBusiness...) for SEO.',
    keywords: ["schema.org","json-ld","donnees structurees","rich snippets","seo"] },
  { slug: 'qr-code', icon: 'QrCode',
    titleFr: 'Generateur de QR Code', titleEn: 'QR Code Generator',
    descFr: 'Creez des QR codes personnalisables (URL, texte, contact) et telechargez-les en PNG.',
    descEn: 'Create customizable QR codes (URL, text, contact) and download them as PNG.',
    keywords: ["qr code","qrcode","generateur qr","code qr"] },
  { slug: 'color-palette', icon: 'Palette',
    titleFr: 'Generateur de palettes de couleurs', titleEn: 'Color Palette Generator',
    descFr: 'Generez des palettes harmonieuses, copiez les codes HEX et exportez vos couleurs.',
    descEn: 'Generate harmonious palettes, copy HEX codes and export your colors.',
    keywords: ["palette","couleurs","hex","design","generateur palette","color"] },
  { slug: 'compound-interest', icon: 'TrendingUp',
    titleFr: 'Calculateur d’intérêts composés', titleEn: 'Compound Interest Calculator',
    descFr: 'Calculez la croissance de votre capital avec intérêts composés et versements réguliers.',
    descEn: 'Calculate your capital growth with compound interest and regular contributions.',
    keywords: ["intérêts composés","placement","épargne","investissement","calculateur"] },
  { slug: 'savings-calculator', icon: 'PiggyBank',
    titleFr: 'Calculateur d’épargne', titleEn: 'Savings Calculator',
    descFr: 'Estimez combien épargner par mois pour atteindre votre objectif financier.',
    descEn: 'Estimate how much to save monthly to reach your financial goal.',
    keywords: ["épargne","objectif","économies","budget","calculateur"] },
  { slug: 'vat-calculator', icon: 'Receipt',
    titleFr: 'Calculateur de TVA', titleEn: 'VAT Calculator',
    descFr: 'Calculez la TVA, le montant HT et TTC avec différents taux personnalisables.',
    descEn: 'Calculate VAT, net and gross amounts with customizable rates.',
    keywords: ["tva","ht","ttc","taxe","calculateur tva"] },
  { slug: 'margin-calculator', icon: 'Percent',
    titleFr: 'Calculateur de marge', titleEn: 'Margin Calculator',
    descFr: 'Calculez votre marge commerciale, le taux de marque et le prix de vente optimal.',
    descEn: 'Calculate your profit margin, markup rate and optimal selling price.',
    keywords: ["marge","marque","prix de vente","rentabilité","commerce"] },
  { slug: 'percentage-calculator', icon: 'Calculator',
    titleFr: 'Calculateur de pourcentages', titleEn: 'Percentage Calculator',
    descFr: 'Calculez pourcentages, augmentations, réductions et variations en un clic.',
    descEn: 'Calculate percentages, increases, discounts and variations in one click.',
    keywords: ["pourcentage","calcul","augmentation","réduction","variation"] },
  { slug: 'invoice-generator', icon: 'FileSpreadsheet',
    titleFr: 'Générateur de factures', titleEn: 'Invoice Generator',
    descFr: 'Créez des factures professionnelles avec lignes, TVA et total, exportables en PDF.',
    descEn: 'Create professional invoices with line items, VAT and total, exportable to PDF.',
    keywords: ["facture","invoice","tva","pdf","générateur facture"] },
  { slug: 'quote-generator', icon: 'FileCheck',
    titleFr: 'Générateur de devis', titleEn: 'Quote Generator',
    descFr: 'Générez des devis clairs avec prestations, montants et validité, prêts à envoyer.',
    descEn: 'Generate clear quotes with services, amounts and validity, ready to send.',
    keywords: ["devis","quote","estimation","pdf","générateur devis"] },
  { slug: 'grade-average', icon: 'GraduationCap',
    titleFr: 'Calculateur de moyenne', titleEn: 'Grade Average Calculator',
    descFr: 'Calculez votre moyenne pondérée par coefficients matière par matière.',
    descEn: 'Calculate your weighted average by coefficients subject by subject.',
    keywords: ["moyenne","notes","coefficient","étudiant","calcul moyenne"] },
  { slug: 'grade-converter', icon: 'ArrowLeftRight',
    titleFr: 'Convertisseur de notes', titleEn: 'Grade Converter',
    descFr: 'Convertissez une note entre les systèmes /20, /100, GPA et lettres (A-F).',
    descEn: 'Convert a grade between /20, /100, GPA and letter systems (A-F).',
    keywords: ["note","conversion","gpa","barème","convertisseur notes"] },
  { slug: 'final-grade', icon: 'Target',
    titleFr: 'Calculateur de note finale', titleEn: 'Final Grade Calculator',
    descFr: 'Déterminez la note nécessaire à l’examen final pour atteindre votre objectif.',
    descEn: 'Find the grade needed on the final exam to reach your target.',
    keywords: ["note finale","examen","objectif","étudiant","calcul note"] },
  { slug: 'image-compress', icon: 'FileImage',
    titleFr: 'Compresseur d’images', titleEn: 'Image Compressor',
    descFr: 'Réduisez le poids de vos images JPG/PNG/WEBP directement dans le navigateur, sans perte de confidentialité.',
    descEn: 'Reduce the size of your JPG/PNG/WEBP images right in your browser, fully private.',
    keywords: ["compression image","réduire image","optimiser","jpg","webp"] },
  { slug: 'image-convert', icon: 'RefreshCw',
    titleFr: 'Convertisseur d’images', titleEn: 'Image Converter',
    descFr: 'Convertissez vos images entre les formats JPG, PNG et WEBP en un clic.',
    descEn: 'Convert your images between JPG, PNG and WEBP formats in one click.',
    keywords: ["convertir image","jpg","png","webp","format image"] },
  { slug: 'image-resize', icon: 'Maximize2',
    titleFr: 'Redimensionneur d’images', titleEn: 'Image Resizer',
    descFr: 'Redimensionnez vos images à la taille souhaitée en conservant les proportions.',
    descEn: 'Resize your images to the desired dimensions while keeping aspect ratio.',
    keywords: ["redimensionner","resize","taille image","pixels"] },
  { slug: 'image-watermark', icon: 'Stamp',
    titleFr: 'Filigrane d’images', titleEn: 'Image Watermark',
    descFr: 'Ajoutez un filigrane texte personnalisable à vos images pour les protéger.',
    descEn: 'Add a customizable text watermark to your images to protect them.',
    keywords: ["filigrane","watermark","protéger image","copyright"] },
  { slug: 'image-crop', icon: 'Crop',
    titleFr: 'Recadrage d’images', titleEn: 'Image Cropper',
    descFr: 'Recadrez vos images aux dimensions exactes ou aux ratios courants (1:1, 16:9, 4:3).',
    descEn: 'Crop your images to exact dimensions or common ratios (1:1, 16:9, 4:3).',
    keywords: ["recadrer","crop","rogner","ratio","image"] },
  { slug: 'text-summarizer', icon: 'AlignLeft',
    titleFr: 'Résumeur de texte', titleEn: 'Text Summarizer',
    descFr: 'Résumez automatiquement un texte long en quelques phrases essentielles.',
    descEn: 'Automatically summarize long text into key sentences.',
    keywords: ["résumé","résumer texte","synthèse","ia","résumeur"] },
  { slug: 'text-rephraser', icon: 'Repeat',
    titleFr: 'Reformulateur de texte', titleEn: 'Text Rephraser',
    descFr: 'Reformulez vos textes pour les rendre plus fluides et professionnels.',
    descEn: 'Rephrase your text to make it smoother and more professional.',
    keywords: ["reformuler","paraphrase","réécrire","ia","reformulateur"] },
  { slug: 'grammar-checker', icon: 'SpellCheck',
    titleFr: 'Correcteur grammatical', titleEn: 'Grammar Checker',
    descFr: 'Corrigez les fautes d’orthographe, de grammaire et de ponctuation.',
    descEn: 'Fix spelling, grammar and punctuation mistakes.',
    keywords: ["correcteur","grammaire","orthographe","ia","correction"] },
  { slug: 'email-generator', icon: 'Mail',
    titleFr: 'Générateur d’e-mails', titleEn: 'Email Generator',
    descFr: 'Rédigez des e-mails professionnels à partir de quelques mots-clés.',
    descEn: 'Write professional emails from a few keywords.',
    keywords: ["email","e-mail professionnel","rédaction","ia","générateur email"] },
  { slug: 'product-description', icon: 'Package',
    titleFr: 'Descriptions produits', titleEn: 'Product Descriptions',
    descFr: 'Générez des descriptions produits vendeuses pour vos boutiques en ligne.',
    descEn: 'Generate compelling product descriptions for your online stores.',
    keywords: ["description produit","e-commerce","vente","ia","fiche produit"] },
  { slug: 'social-post', icon: 'Share2',
    titleFr: 'Posts réseaux sociaux', titleEn: 'Social Media Posts',
    descFr: 'Créez des publications engageantes avec hashtags pour vos réseaux.',
    descEn: 'Create engaging posts with hashtags for your social networks.',
    keywords: ["post","réseaux sociaux","community","ia","publication"] },
  { slug: 'youtube-title', icon: 'Youtube',
    titleFr: 'Titres YouTube', titleEn: 'YouTube Titles',
    descFr: 'Générez des titres YouTube accrocheurs et optimisés pour le clic.',
    descEn: 'Generate catchy, click-optimized YouTube titles.',
    keywords: ["titre youtube","accroche","clic","ia","youtube"] },
  { slug: 'hashtag-generator', icon: 'Hash',
    titleFr: 'Générateur de hashtags', titleEn: 'Hashtag Generator',
    descFr: 'Trouvez les hashtags les plus pertinents pour booster votre visibilité.',
    descEn: 'Find the most relevant hashtags to boost your visibility.',
    keywords: ["hashtag","tags","visibilité","ia","instagram"] },
  { slug: 'jpg-to-pdf', icon: 'FileImage',
    titleFr: 'JPG en PDF', titleEn: 'JPG to PDF',
    descFr: 'Convertissez une ou plusieurs images JPG/PNG en un fichier PDF, directement dans votre navigateur.',
    descEn: 'Convert one or more JPG/PNG images into a single PDF, right in your browser.',
    keywords: ["jpg en pdf","image en pdf","convertir pdf","png pdf"] },
  { slug: 'pdf-merge', icon: 'Combine',
    titleFr: 'Fusionner des PDF', titleEn: 'Merge PDF',
    descFr: 'Combinez plusieurs fichiers PDF en un seul document, sans envoi sur un serveur.',
    descEn: 'Combine multiple PDF files into a single document, with no server upload.',
    keywords: ["fusionner pdf","merge pdf","combiner pdf","assembler pdf"] },
  { slug: 'pdf-split', icon: 'Scissors',
    titleFr: 'Découper un PDF', titleEn: 'Split PDF',
    descFr: 'Extrayez une plage de pages d’un PDF dans un nouveau fichier.',
    descEn: 'Extract a range of pages from a PDF into a new file.',
    keywords: ["découper pdf","split pdf","extraire pages","diviser pdf"] },
  { slug: 'pdf-rotate', icon: 'RotateCw',
    titleFr: 'Pivoter un PDF', titleEn: 'Rotate PDF',
    descFr: 'Faites pivoter toutes les pages d’un PDF de 90, 180 ou 270 degrés.',
    descEn: 'Rotate all pages of a PDF by 90, 180 or 270 degrees.',
    keywords: ["pivoter pdf","rotation pdf","rotate pdf","tourner pages"] },
  { slug: 'pdf-watermark', icon: 'Stamp',
    titleFr: 'Filigrane PDF', titleEn: 'PDF Watermark',
    descFr: 'Ajoutez un filigrane texte sur toutes les pages d’un PDF pour le protéger.',
    descEn: 'Add a text watermark on every page of a PDF to protect it.',
    keywords: ["filigrane pdf","watermark pdf","protéger pdf","tampon"] },
];

export const getTool = (slug: string) => tools.find(t => t.slug === slug);